### PR TITLE
Re-install apps with APK splits if they are compatible

### LINKED ISSUE #91: Apps using app bundles crash after getting restored
Some apps do get installed on a restore, but they crash immediately when you try to launch them.

Need to uninstall and reinstall to get them working.

I've seen this with Twitter, and then some other app prompted me to something about needing Google Play to get the needed updates. This was also faced by somebody on #CalyxOS:matrix.org

I think this could be related to split APKs, need to check.

I do have a backup that can reproduce this, will get logs.

### PR DESCRIPTION
**Pull request by grote**
This is the second part of #144 and builds upon this work to properly re-install apps even if they have APK splits. It introduces a compatibility checker which only looks at screen density and cpu architecture for now. This would work for all the splits I've seen so far. Unusual splits can be reported with https://gitlab.com/grote/app-bundle-reporter

More details as always can be found in the individual commit messages.

Fixes #91

### CODE REVIEW

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt [hunk 1]
```diff
@@ -0,0 +1,118 @@
...
+import android.content.Context
+import android.os.Build
+import android.util.Log
+
+private const val TAG = "SplitCompatChecker"
+
+private const val CONFIG_PREFIX = "config."
+private const val CONFIG_LENGTH = CONFIG_PREFIX.length
+
+private const val LDPI_VALUE = 120
```
Comment (chirayudesai) [inline app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:12]: You should add a link to the source here, https://github.com/google/bundletool/blob/1.2.0/src/main/java/com/android/tools/build/bundletool/model/utils/ResourcesUtils.java#L72

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt [hunk 2]
```diff
@@ -0,0 +1,118 @@
...
+class DeviceInfo(context: Context) {
+    val densityDpi: Int = context.resources.displayMetrics.densityDpi
+    val supportedABIs: List<String> = Build.SUPPORTED_ABIS.toList()
+}
+
+/**
+ * Tries to determine APK split compatibility with a device by examining the list of split names.
+ * This only looks on the supported ABIs and the screen density.
+ * Other config splits e.g. based on OpenGL or Vulkan version are also possible,
+ * but don't seem to be widely used, so we don't consider those for now.
```
Comment (chirayudesai) [inline app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:29]: I feel like we've only gone through a small subset of apps, I don't remember seeing any newer games on the list which would be most likely to utilize such a split.

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt [hunk 3]
```diff
@@ -0,0 +1,118 @@
...
+     * and false otherwise.
+     */
+    fun isCompatible(splitNames: Collection<String>): Boolean = splitNames.all { splitName ->
+        // all individual splits need to be compatible (which can be hard to judge by name only)
+        isCompatible(splitName)
+    }
+
+    private fun isCompatible(splitName: String): Boolean {
+        val index = splitName.indexOf(CONFIG_PREFIX)
+        // If this is not a standardized config split, we just assume that it will work,
```
Comment (chirayudesai) [inline app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:63]: I feel like this is the wrong assumption to make here.

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt [hunk 4]
```diff
@@ -0,0 +1,118 @@
...
+        }
+
+        // Check if this is a known screen density config
+        densityMap[name]?.let { splitDensity ->
+            // the split's density must not be much lower than the device's.
+            return isDensityCompatible(splitDensity)
+        }
+
+        // At this point we don't know what to make of that split,
+        // so let's just hope that it will work. It might just be a language.
```
Comment (chirayudesai) [inline app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:85]: We can handle languages like abi and density too, and the bundletool class linked above has some relevant code too.

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt [hunk 5]
```diff
@@ -0,0 +1,118 @@
...
+        Log.v(TAG, "Unhandled config split '$splitName'. Assuming it is ok.")
```
Comment (chirayudesai) [inline app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:86]: That would then mean that we can assume otherwise, unless it's the same device model.

**Review by chirayudesai — CHANGES_REQUESTED** [review]
I feel like we may not want to just treat any random splits as compatible all the time, but do it only when the device is the same.

Which is why I mentioned handling languages in that config, as that means we've then handled the most common of splits.

OpenGL/Vulkan wasn't seen so far, but I imagine that could be the next common target once we started seeing it as that's something generic and not app specific.

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt (hunk 1 above)
Comment (grote) [reply app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:12]: Even if I took those numbers from https://developer.android.com/training/multiscreen/screendensities#TaskProvideAltBmp ?

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt (hunk 2 above)
Comment (grote) [reply app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:29]: I checked several games on apk mirror, but most just used arch based splits, some also languages. Please try to find more. I agree that it would be best to have a much larger data basis for this.

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt (hunk 3 above)
Comment (grote) [reply app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:63]: Possibly true, but please provide examples here where the assumption is wrong.

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt (hunk 4 above)
Comment (grote) [reply app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:85]: We could, but what would be the benefit?

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt (hunk 1 above)
Comment (chirayudesai) [reply app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:12]: Yes. :trollface:

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt (hunk 3 above)
Comment (chirayudesai) [reply app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:63]: Assuming something unknown just works is wrong was my point.

I don't think we have sufficient data yet to make that claim, and till since we already have a link to store solution, that'd work well.

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt (hunk 4 above)
Comment (chirayudesai) [reply app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:85]: Read the comment below, or the github comment of the full review

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt [hunk 6]
```diff
@@ -0,0 +1,134 @@
...
+private const val MDPI_VALUE = 160
+private const val TVDPI_VALUE = 213
+private const val HDPI_VALUE = 240
+private const val XHDPI_VALUE = 320
+private const val XXHDPI_VALUE = 480
+private const val XXXHDPI_VALUE = 640
+
+/**
+ * Tries to determine APK split compatibility with a device by examining the list of split names.
+ * This only looks on the supported ABIs and the screen density.
```
Comment (chirayudesai) [inline app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:21]: and language now

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt [hunk 7]
```diff
@@ -0,0 +1,134 @@
...
+            return true
+        }
+
+        // At this point we don't know what to make of that split
+        return if (deviceInfo.isSameDevice(deviceName)) {
+            // so we only allow it if it came from the same device
+            Log.v(TAG, "Unhandled config split '$splitName'. Came from same device.")
+            true
+        } else {
+            Log.w(TAG, "Unhandled config split '$splitName'. Not allowed.")
```
Comment (chirayudesai) [inline app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:101]: Would we want to allow these when `unknownAllowed` is true?

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/DeviceInfo.kt [hunk 8]
```diff
@@ -0,0 +1,27 @@
...
+import android.content.Context
+import android.os.Build
+import com.android.internal.app.LocalePicker
+import com.stevesoltys.seedvault.R
+
+class DeviceInfo(context: Context) {
+    val densityDpi: Int = context.resources.displayMetrics.densityDpi
+    val supportedABIs: List<String> = Build.SUPPORTED_ABIS.toList()
+    private val deviceName: String = "${Build.MANUFACTURER} ${Build.MODEL}"
+    private val languages = LocalePicker.getSupportedLocales(context)
```
Comment (chirayudesai) [inline app/src/main/java/com/stevesoltys/seedvault/restore/install/DeviceInfo.kt:12]: We could add a comment here about what we based this on to make future updates easier

File: app/src/main/res/values/strings.xml [hunk 9]
```diff
@@ -118,6 +118,8 @@
     <string name="restore_installing_tap_to_install">Tap to install</string>
     <string name="restore_next">Next</string>
     <string name="restore_restoring">Restoring backup</string>
+    <string name="restore_restoring_error_title">Not all apps restored</string>
+    <string name="restore_restoring_error_message">You can still try to re-install these apps later with "auto restore" turned on to get their data restored.</string>
```
Comment (chirayudesai) [inline app/src/main/res/values/strings.xml:122]: This is where apk install worked but app data restore failed right?

We could tweak this message a bit, it's already quite long but also sounds confusing.

**Review by chirayudesai — APPROVED** [review]
Just some minor comments inline, looks good otherwise.

**Comment by chirayudesai** [comment]
Oh and I'm yet to test this.

@grote did you try a full SetupWizard restore sequence with this yet?

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt (hunk 7 above)
Comment (grote) [reply app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:101]: I think this is too risky as there can be lots of crazy splits and we have no way to check compatibility here.

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/DeviceInfo.kt (hunk 8 above)
Comment (grote) [reply app/src/main/java/com/stevesoltys/seedvault/restore/install/DeviceInfo.kt:12]: What do you mean?

File: app/src/main/res/values/strings.xml (hunk 9 above)
Comment (grote) [reply app/src/main/res/values/strings.xml:122]: > This is where apk install worked but app data restore failed right?

This is shown after data restore when there are aps whose data could not be restored because they were not installed, but we have data in the backup for auto-restore later.

Suggestions for how to improve it are most welcome!

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/DeviceInfo.kt (hunk 8 above)
Comment (chirayudesai) [reply app/src/main/java/com/stevesoltys/seedvault/restore/install/DeviceInfo.kt:12]: Nevermind.

File: app/src/main/res/values/strings.xml (hunk 9 above)
Comment (chirayudesai) [reply app/src/main/res/values/strings.xml:122]: @mikeNG thoughts?

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt (hunk 7 above)
Comment (chirayudesai) [reply app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:101]: Ok so unknown splits are ok if enabled, unless they're unknown config.* splits, since for those we have a well-defined list of what we accept. Right?

**Review by stevesoltys — APPROVED** [review]

File: app/src/main/res/values/strings.xml (hunk 9 above)
Comment (mikeNG) [reply app/src/main/res/values/strings.xml:122]: Does the user see which applications failed? If yes, then maybe this sounds better?

Unable to restore some apps
You can reinstall these apps manually and "Automatic restore" will attempt to restore their data.

File: app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt (hunk 7 above)
Comment (grote) [reply app/src/main/java/com/stevesoltys/seedvault/restore/install/ApkSplitCompatibilityChecker.kt:101]: Right.

**Review by chirayudesai — APPROVED** [review]
